USE [MCIODM]
GO

/****** Object:  Table [dbo].[stgStorageCPUShorttermForecast]    Script Date: 1/30/2017 2:48:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[stgStorageCPUShorttermForecast](
	[SnapshotDate] [datetime] NULL,
	[Geo] [nvarchar](max) NULL,
	[Region] [nvarchar](max) NULL,
	[ClusterType] [nvarchar](max) NULL,
	[ResourceUnit] [nvarchar](max) NULL,
	[ForecastDate] [datetime] NULL,
	[ForecastValue] [float] NULL,
	[SangamAutoGeneratedIDColumn] [bigint] IDENTITY(1,1) NOT NULL
)

GO
